### ISSUE TITLE
此离线地图能否实现搜索功能

### ISSUE THREAD

**Issue by chenwuwen** [muxfe/bmap-offline-for-web#1]
如题，离线地图下载到本地文件，还是数据库，是否可以实现离线搜索功能

**Comment by muxfe** [comment]
这里的离线地图是指 web 端的瓦片图，存储在文件系统。当然如果能够映射静态资源与路径的关系，也可以转存到数据库。全部缩放层级下的瓦片图数量是非常大的。

关于搜索试了一下，发现每次搜索是要调用百度地图api的，应该无法离线化。

**Comment by chenwuwen** [comment]
我找到了一个方法，在地图下载器里下载哪个地图，如在地图下载器下载的是高德地图，那么在网上去找一些高德地图的poi数据信息，将其导入本地数据库，这样也可以实现搜索功能，当然我说的就是局域网，这几天我已经实现了这个Demo
https://github.com/chenwuwen/OffineMap

**Comment by muxfe** [comment]
我当时做这个也是因为项目需求，部署环境不能访问外网。做的比较简单，只是篡改百度地图 api 里面请求瓦片图的链接然后导向本地。项目里没有本地搜索的需求，倒是有个路径规划的需求，这个感觉不容易离线化，没有再进一步考虑。
